target("llaisys-device-nvidia")
    set_kind("static")
    set_languages("cxx17", "cuda")
    set_warnings("all", "error")
    add_cuflags("-Xcompiler=-fPIC")
    add_files("../src/device/nvidia/*.cu")
    add_links("cudart")
    on_install(function (target) end)
target_end()

target("llaisys-ops-nvidia")
    set_kind("static")
    add_deps("llaisys-tensor")
    set_languages("cxx17", "cuda")
    set_warnings("all", "error")
    add_cuflags("-Xcompiler=-fPIC")
    add_files("../src/ops/*/nvidia/*.cu")
    add_links("cudart")
    on_install(function (target) end)
target_end()
